services:
  postgres:
    build: postgres/.
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=db

  python:
    build: python/.
    ports:
      - 8000:8000
    depends_on:
      - postgres